### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by JJBocanegra** [javieros105/FVTT-TokenHUDWildcard#10]
I can't see the icon or the wildcard checkbox, is this normal? Maybe is not working with newer versions?

**Comment by javieros105** [comment]
That's weird, it's actually working for me. What version of foundry and what system are you using?

**Comment by rmasoni** [comment]
The wildcard checkbox is only present on actors' prototype tokens, not on tokens that are already placed on a scene.

<img width="991" alt="image" src="https://user-images.githubusercontent.com/62244/112087735-462d4480-8b6d-11eb-8e79-55c108818e0e.png">

Prototype token on the left, placed token configuration on the right.

I just tested with 0.7.9 and it's working normally.

**Comment by javieros105** [comment]
Thanks @rmasoni . Didn't think of that being the issue, the module has to be configured through the prototype token, it won't show on the token configuration of a placed token.

I'm going to close the issue, but if this is not the problem or you continue having issues I will open it again
