### ISSUE TITLE
Issue with irregular shaped images

### ISSUE THREAD

**Issue by ironmonk108** [javieros105/FVTT-TokenHUDWildcard#13]
If the image isn't even sided, then it looks squashed when displayed.

Adding an `object-fit: contain;` to line 48 should fix it.

**Comment by javieros105** [comment]
thanks for reporting this, I've been really busy so i don't know when I'll be able to fix it and upload but I'll try to not make it too long.

**Comment by javieros105** [comment]
arbron already fixed this and I upload the update
