### ISSUE TITLE
Default Token doesn't work in 0.8

### ISSUE THREAD

**Issue by GambetTV** [javieros105/FVTT-TokenHUDWildcard#15]
I know this hasn't been updated in a while, but for the most part it seems to still work even in 0.8, save for one major thing, which is filling out the Default Image for the Wildcard drop default field doesn't do anything. Not sure how complicated of a fix this would be, but if it's possible it would be great!

**Comment by tjlanza** [comment]
I can confirm this issue. In fact, it's what I came here to report.

**Comment by Dick-K** [comment]
Can confirm.

**Comment by chklein1** [comment]
I too came here to report the same issue. For now I've had to disable wildcard tokens altogether, but it would be great to re-enable things. Other than Default Token, everything seems to work fine in 0.8.6.

**Comment by javieros105** [comment]
Sorry for all the delays, I kinda left this module to the side because of being too busy and not knowing there was actual interest in it. arbron did a PR fixing this and I already made the update for the module.

**Comment by Dick-K** [comment]
I've just updated to 1.3.0 and the default token is still not being applied...a token is simply chosen at random as if no default existed.

Edit: works fine in Foundry 0.7.10, fails in 0.8.6

**Comment by chklein1** [comment]
Module version 1.3.0 on 0.8.6 retains the same behavior as before, with the "Wildcard drop default" field being ignored.

**Comment by javieros105** [comment]
that's strange because it's working for me with default image. Maybe I messed up upl.oading the update? Can you check in foundry setup if the module is actually version 1.3.0?

**Comment by Cup-of-Coffee** [comment]
It appears to be version 1.3.0 (I'm using Foundry version 8.6.0).

![Screenshot 2021-06-12 182306](https://user-images.githubusercontent.com/39238717/121790231-3e4cd180-cbab-11eb-8508-e76e363abea5.png)

I am also having this issue. I knew about it before the update to 1.3.0, and it still seems to be there now, after updating.

**Comment by chklein1** [comment]
I can also confirm that the module version reports 1.3.0 as expected.

**Comment by Dick-K** [comment]
Yes, version is 1.3.0 - deactivated all other modules.

**Comment by javieros105** [comment]
Are you guys using DnD5e or pathfinder?

**Comment by Cup-of-Coffee** [comment]
> 
> 
> Are you guys using DnD5e or pathfinder?

I'm using Pathfinder 2e.

**Comment by Dick-K** [comment]
Neither, Call of Cthulhu 7e.

**Comment by javieros105** [comment]
Ok, yeah it's an issue with Pathfinder 2e at least, I think it has to do with the preCreateHook that sets the img property of the token in case the default field was filled. I'm going to try and fix that as soon as possible

**Comment by Dick-K** [comment]
Thanks a lot for looking into this, much appreciated.

**Comment by chklein1** [comment]
I'm running DnD5e 1.3.3

**Comment by tjlanza** [comment]
1.3.0 appears to works fine in SR5 0.7.17

Thanks!

**Comment by javieros105** [comment]
Ok, so it's weird that it's not working for some in DnD5e, as I haven't had problems myself, I will need to keep on checking it. For now I found that one solution that could work for every system could be to change the hook from preCreateToken to createToken, as I think that the problem could be that with preCreateToken it's setting the image before triggering the wildcard function.

```js
Hooks.on('createToken', (token, data, options, userId) => {
    const is080 = !isNewerVersion("0.8.0", game.data.version)
    const defaultValue = token?.actor?.data?.token?.flags['token-hud-wildcard'] ? token.actor.data.token.flags['token-hud-wildcard'].default : ''
    if (defaultValue !== '' && token?.actor?.data?.token?.randomImg) {
        const updateTarget = is080 ? token.document : token
        token.update({ img: defaultValue })
    }
})
```

I'm trying to work a better solution, if anyone has input on this it would be appreciated as I'm not really sure this is gonna work for every system or foundry version

**Comment by szefo09** [comment]
```js
        Hooks.on('preCreateToken', (token, data, options, userId) => {
            const actor = token.actor
            const defaultValue = data.flags['token-hud-wildcard'] ? data.flags['token-hud-wildcard'].default : ''
            if (defaultValue !== '' && actor?.data.token.randomImg) {
                token.data.update({img:defaultValue});
            }
        })
```
this works for 0.8.7

**Comment by javieros105** [comment]
Ok tried it and strangely enough it works for PF2 but it's not working for DnD5e. I will try to find why, but uploaded version 1.3.1 that makes this change. If you update and use 5e you will lose this functionality, I'll try to find out how to make it work for all as soon as possible.

**Comment by szefo09** [comment]
Interesting. The line works just fine for 0.8.7 foundry and d&d 1.3.5, always gives me the selected image.

**Comment by chklein1** [comment]
I just tried your 1.3.1 update using Foundry 0.8.7 and DnD5e 1.3.5 and the problem no longer repros (thanks!). Are you testing with the latest game system version?

**Comment by javieros105** [comment]
Yeah, it's Wei d because if I excecute that as a Macro it works but through the module it throws me an error, maybe it's just my case

**Comment by javieros105** [comment]
I found the problem, default image is incompatible with token mold
