### ISSUE TITLE
Default Token doesn't work in 0.8

### ISSUE THREAD

**Issue by GambetTV** [javieros105/FVTT-TokenHUDWildcard#16]
Apologies for reposting. The last post got closed, but the issue seems to still be present. Essentially using the Default Token option in 0.8.6 doesn't function, and it will simply randomize the images. This issue is not present in 0.7.10, however.

**Comment by javieros105** [comment]
I reopened the other one #15  so I'll close this one to keep track on one only. I'm working on it, I think I found the problem I need to clean the code and test it a bit more then I'll make an update
