### ISSUE TITLE
Default Token not working

### ISSUE THREAD

**Issue by LeokaiSkarri** [javieros105/FVTT-TokenHUDWildcard#17]
I have some PCs with multiple tokens, even if I selected a default one, the tokens are still randomized.

**Comment by Milkhare** [comment]
> I have some PCs with multiple tokens, even if I selected a default one, the tokens are still randomized.

Try to disable another token modules. Token Mold broke this thing in my case

**Comment by LeokaiSkarri** [comment]
Yep, this worked fine for me, thank you ^^
