### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by JulianTierno** [javieros105/FVTT-TokenHUDWildcard#18]
I just dowload and install without any conflict or message, but it seems that dont work for players. Nor HUD icon nor token with wildacrd active. Any idea what happen or I could do it wrong?

**Comment by javieros105** [comment]
Let me check it out. What version of Foundry and which system are you using?

**Comment by V3rotti** [comment]
i'm running 8.8 and the HUD Icon works but the wildcard image will not be chosen, even though it is set in the Token...

**Comment by javieros105** [comment]
That's really strange because I'm using 0.8.8 and 5e 1.3.6 and it works perfectly. It could be a different module that is conflicting or maybe the game system. Could you check by trying the module without other modules active?

**Comment by V3rotti** [comment]
i checked the modules and it seems to collide with token Mold by Moerill which is very unfortunate

**Comment by javieros105** [comment]
ahh, yes, I found that conflict for me too. Sadly for now I have no way of making it compatible. It had issues with updating the token image both by the panel and when using the default image field for my mod. I think it has to do with the order the hooks are excecuted, I think token mold excecutes at the end and it sets the image according to size configurations from token mold even if there is no change so it undos the changes by my mod
