### ISSUE TITLE
Enhancement: Thumbnail Images

### ISSUE THREAD

**Issue by Dumbhuman** [javieros105/FVTT-TokenHUDWildcard#2]
I think this module is a great idea!  My first thought for a potential feature enhancement is one that you've probably thought about already: adding a thumbnail of the image in addition to (or instead of) the filename.  Depending on how you're able to lay out the thumbnails (hopefully in both rows and columns), you could potentially accommodate a lot more choices on the screen at once.

**Comment by javieros105** [comment]
Hey, thanks for your suggestion! I actually didn't even thing about that, could be a better way to show each available token, I like it.

Gonna try to add that functionality for next update, maybe allow in settings to decide if you want to show thumbnails or just the name

**Comment by javieros105** [comment]
Enhancement done! Now you can choose between list of files or image thumbnails in the settings (default is images). But also added some nice functionality for picking a default token for dropping on canvas so it's not randomized
