### ISSUE TITLE
Token Mold Conflict with default Image

### ISSUE THREAD

**Issue by jacksands** [javieros105/FVTT-TokenHUDWildcard#20]
Hello, tks for the amazing module and the new scale property!
I bumped into a conflict with token mold, the default image do not apply, keeps radom...
It only works returning to version 1.3.0 of TH Wildcards...
no settings prevent that...
I alredy removed TK mold, but can you take a look if you don't mind?

TKS!

**Comment by javieros105** [comment]
hey, yeah I know about that compatibility. Thanks for letting me know that an older version actually works with token mold. Haven't had the time to look more in depth on it but I'll try to do it soon

**Comment by jacksands** [comment]
I Don't know if this can help, but a friend how made some modules told me that using the module lib-wrapper prevents one module to interfering with one another. I don't know how, really not on this binary black magic, but it is a suggestion.

**Comment by Fridan99** [comment]
I also have this error 1.4.0 Token HUD Wildcard

**Comment by javieros105** [comment]
I finally have some time to work on this, I'll try to make the compatibility using the lib wrapper, hopefully during this week

**Comment by jacksands** [comment]
Hi friend! any news? this is one issue that I wish you success in solving it soon!

**Comment by javieros105** [comment]
I haven't been able to solve it. Had to read and look for examples on how the wrapper is used, I'll try to make the wrapper in local and see if it works with a simple one, once that's tested I'll let you guys know

**Comment by javieros105** [comment]
Sadly, token mold doesn't use the lib wrapper and I tried using the createToken hook instead of the preCreateToken hook but it you lose the dimensions of the image set up and the image is still not setting properly. So I'm stuck at how to solve it

**Comment by Fridan99** [comment]
Maybe someone in discord can give you some ideas on how to get around the problem.

#module-troubleshooting

**Comment by javieros105** [comment]
Scratch that, managed to fix it I think. I just had to change a bit how I referenced the token to update on the hook, since the hook references the parent and not the token data I wasn't able to direclty update values. I will update in a few minutes

**Comment by Fridan99** [comment]
Nice

**Comment by javieros105** [comment]
It's been updated

**Comment by jacksands** [comment]
Just tested and works perfectly!!! tks!!!! really appreciate the effort!
