### ISSUE TITLE
Issue using .webp images

### ISSUE THREAD

**Issue by KevinRichard-GM** [javieros105/FVTT-TokenHUDWildcard#21]
I starting using this module and I got it to work for a couple tokens but for one token in particular with I try to assign the wildcard and set the default image it won't let me click the "Update Token" button. The button highlights on mouse over but clicking it does nothing.

The only difference I can see is that the tokens for this one are .webp instead of the .png that were used with the other tokens that appear to work fine.

UPDATE: Disregard, it appears to be an issue with the Update Token button now not only with trying to use the Wildcard Module. I'm troubleshooting possible issues created by another module.

**Comment by javieros105** [comment]
I'll try to check if from my side and let you know if I find something

**Comment by javieros105** [comment]
Did you find the issue? Just to know
