### ISSUE TITLE
Feature Request: Copy & Paste current token image

### ISSUE THREAD

**Issue by GambetTV** [javieros105/FVTT-TokenHUDWildcard#23]
Right now every time I use Ctrl + C and Ctrl + P to copy and paste a new token onto the map, it reverts automatically to the default image, even if a different one is selected that I'm copying from. Is there a way you could save us time by having it copy the current image?

**Comment by javieros105** [comment]
With the older version it worked right?

**Comment by GambetTV** [comment]
I am currently using version 1.4 due to the bugs of 1.5, and even in 1.4 C&Ping tokens causes them to revert to their default image. I do want to say that in a previous version this worked though, but TBH I can't remember what version that was.

**Comment by javieros105** [comment]
ahh yeah, I can see the problem. I'm gonna have to check if it's possible to detect on a createToken hook if it was pasted or drag and drop, but I don't know yet how I'm gonna fix it

**Comment by javieros105** [comment]
Had a chance to check if it was possible, but I can't find a way to detect if in the hook that i'm doing the image update it's through copy pasting or not. This is both on createToken hook and on preCreateToken hook, so I'm gonna close it. If someone finds a way I will open it again and take it
