### ISSUE TITLE
Critical Bug: module.json in master and releases broken

### ISSUE THREAD

**Issue by adotor** [javieros105/FVTT-TokenHUDWildcard#25]
All your module.jsons (for the master and releases) are broken. Each release installs always the latest build and updates always pull it - so your module does not work with previous foundry versions (e.g. 0.7.10).

1) Incorrect download url
Even previous releases download the latest version, as you refer in each module.json:

`https://github.com/javieros105/FVTT-TokenHUDWildcard/raw/master/token-hud-wildcard.zip`

Each release has to download from the release branch, e.g.:

`https://github.com/javieros105/FVTT-TokenHUDWildcard/raw/v1.3.0/token-hud-wildcard.zip`

2) Incorrect minimum versions
The minimum core version is always 0.6.0 so when updating it always installs the latest version, even if your foundry is incompatible.

You minimum core version has to match the real requirements, e.g.

`"minimumCoreVersion": "0.8.0",`

**Comment by javieros105** [comment]
ooof yeah you are totally right. I'm gonna have to reestructure some stuff

**Comment by javieros105** [comment]
If you have any suggestion it would be really appreciated

Update: I'm just dumb. I should just upload the files to the release and use those links in the package administrator. That was just idiotic. I'm gonna try to fix at least the last 2 versions and future versions will be done that way.

**Comment by javieros105** [comment]
There we go, 1.4.0 and 1.5.0 should be working correctly now!
