### ISSUE TITLE
Broken image link with video

### ISSUE THREAD

**Issue by Bryn1701** [javieros105/FVTT-TokenHUDWildcard#4]
First of all, thank you for an amazing module. It's a must have for me! 

As the title says, when using multiple files, of which some are webm files. It seems to show a broken image link.  Here is an example. https://gyazo.com/2afc04e5ac90ccbde78a88df8c0c721f

**Comment by javieros105** [comment]
In version 1.2.0 added support for animated tokens so now the 3 formats supported by Foundry should be visible in preview (.mp4, .m4v and .webp)
