### ISSUE TITLE
Bug: Installation failed

### ISSUE THREAD

**Issue by paddy74** [javieros105/FVTT-TokenHUDWildcard#5]
I am unable to install the module.

Attempting to install the module by clicking the "install" button results in the following error:
![Capture2](https://user-images.githubusercontent.com/14883939/97112382-57efe600-16ba-11eb-82e0-639d461beb17.PNG)

Attempting to install the module by linking directly to the manifest URL results in the following error:
![Capture](https://user-images.githubusercontent.com/14883939/97112399-6dfda680-16ba-11eb-8ae2-eaaf0eda33da.PNG)

**Comment by javieros105** [comment]
I think that's an error for a different module, that module is Token Hotbar

**Comment by paddy74** [comment]
Ah, my bad. Too many tabs open at once.

**Comment by javieros105** [comment]
No proble, still if you have an issue with mine I'll try to help as much as I can
