### ISSUE TITLE
HUD only showing 2 columns of images

### ISSUE THREAD

**Issue by SpaceOttersea** [javieros105/FVTT-TokenHUDWildcard#7]
When attempting to use the token HUD, only 2 columns of images show up, instead of the intended 3. There is a space to the right of the images, but it appears to be too small for another column to fit. Tested with no other modules installed. 

![Screenshot 2021-01-29 113134](https://user-images.githubusercontent.com/24861047/106313548-a1a21c80-6225-11eb-9aab-448c618ec31e.jpg)

**Comment by rmasoni** [comment]
You probably have your browser set to a different zoom level.

**Comment by javieros105** [comment]
Sorry for the delay, but as @rmasoni mentioned it's probably that. I'm going to check though to make sure

**Comment by javieros105** [comment]
Ok no, I found the problem, it's actually the scrollbar, that scrollbar is different from the one I designed the mod for. I didn't know there was a different scrollbar at all. What version of Foundry do you have and what game system is it?
