### ISSUE TITLE
Series of errors when loading.

### ISSUE THREAD

**Issue by mrjaksauce** [javieros105/FVTT-TokenHUDWildcard#8]
![image](https://user-images.githubusercontent.com/68178310/107846346-e940bf00-6e47-11eb-9486-dadac3303a45.png)

I get this error 6 times every time I refresh foundry. What's happening here? Is it an issue? If not, all good! Close this :)

**Comment by javieros105** [comment]
Sorry for the delay, been hard to keep up with lots of stuff this last few weeks. I don't have that issue myself, and it looks like it involves multilevel, are you sure that error is related to this mod? maybe it might be some incompatibilities
