### ISSUE TITLE
Players cannot see Icon

### ISSUE THREAD

**Issue by HaydenReeve** [javieros105/FVTT-TokenHUDWildcard#9]
Hi,

My players are having some issues seeing the Wardrobe Change icon. Is there a permission or setting that must be set so the players can see this?

The module is otherwise incredible and quite literally exactly what I've always wanted. Thank you so much!

**Comment by javieros105** [comment]
Sorry for the delay, it's been a crazy month and missed all these issues.

It's working for me if the player is the owner of the character, what system are you using?.

Glad you like my little mod

**Comment by HaydenReeve** [comment]
Hey @javieros105, thanks for responding!

Players, even owners of tokens, aren't able to see the icon at all. GM's, or Co-GM's (the two highest permissions) are able to see the icon without issue.

We're using the Pathfinder1e system, which perhaps might assist in your efforts.

I have attached two pictures below. The first picture demonstrates the comparison difference between player and GM with other modules active, while the second is with only TokenHUDWildcard active.

![image](https://user-images.githubusercontent.com/39004735/112142889-1a17cf00-8c12-11eb-9d82-773e88753552.png)
![image](https://user-images.githubusercontent.com/39004735/112142896-1b48fc00-8c12-11eb-87e4-70a4aa932f08.png)

Hopefully, this information is helpful!

**Comment by javieros105** [comment]
Thanks for the images and the info, I'll check it with PF and see what I can do and I'll let you know

**Comment by Shuggaloaf** [comment]
I seem to be having the same issue with the D&D 5e System. Works perfectly for me (GM). Icon appears in right-click menu and I am able to select different images. Players can't see icon at all.

**Comment by javieros105** [comment]
This is an empty world with only the token hud wildcard mod in 5e 
![image](https://user-images.githubusercontent.com/62261473/113175394-c1ec5880-9221-11eb-993b-0c69ec9c8bad.png)

And this is in an empty world with only this mod in pathfinder1
![image](https://user-images.githubusercontent.com/62261473/113175969-62427d00-9222-11eb-8b4b-93627fce89e0.png)

Could you guys check the developer console in the player side if there is any error?

**Comment by HaydenReeve** [comment]
This is a quick screencap of the developer console open opening the token menu.

![image](https://user-images.githubusercontent.com/39004735/113190787-50e38a00-928f-11eb-8e21-c710a5201bc1.png)

Although, I further seem to have located the issue, and while I suppose it makes sense—I do hope there is a workaround.

![image](https://user-images.githubusercontent.com/39004735/113191155-c9e2e180-928f-11eb-8dea-35a0184bf344.png)

Any tokens stored within the world-level folder of the FoundryVTT library are hidden from players by default. Restricted. Since this is a blanket rule, you either allow all players to access these folders or deny it completely from everyone.

Unrestricting privacy of this folder allows players to view the token button as expected.

![image](https://user-images.githubusercontent.com/39004735/113191378-0adaf600-9290-11eb-904c-0e140023cdab.png)

This means any NPCs or Tokens or Players Actors controlled by players must require all users to have library access to the resources for the tool to work.

That... Makes sense, although is a shame.

**Comment by javieros105** [comment]
Ohhh yeah that makes sense. I just confirmed it and if the folder where the images for wildcard are in privacy mode it doesn't work for the player. In this case I can't do anything about it and it actually makes sense for it to work this way

**Comment by Shuggaloaf** [comment]
Sorry for the late reply. Mine are not in a world folder but are in a folder in user data. So yeah that makes sense. 

Is there someway to host these online maybe? I'm wondering if it's stored somewhere with public access if it would solve the issue? Or some other way to only give permission to a single folder?

I can also try some testing for that myself tonight.

**Comment by javieros105** [comment]
@Shuggaloaf  Check if the folder you want to use has this toggled on 
![image](https://user-images.githubusercontent.com/62261473/113339698-42ce5180-9301-11eb-85c1-82f45821b725.png)

It should look like this if you want your players to get the icon, also check that the root folders are not private
![image](https://user-images.githubusercontent.com/62261473/113339782-5b3e6c00-9301-11eb-91c3-15eacd5513ae.png)

**Comment by Shuggaloaf** [comment]
Thanks or the instructions Javieros! 
Hoping I can create a top level folder so they don't have to have access to the whole directory. 
I will check this out and let you know!
